
if (isFrlg(uuid)) {
    return &kFrlgPack;
}
if (uuid == kRubyUsUuid || uuid == kRubyUs11Uuid || uuid == kSapphireUsUuid) {
    return &kRsPack;
}
if (uuid == kEmeraldUsUuid) {
    return &kEmPack;
}
if (uuid == kDiamondUsUuid || uuid == kPearlUsUuid) {
    return &kDpPack;
}
if (uuid == kPlatinumUsUuid || uuid == kPlatinumUs11Uuid) {
    return &kPtPack;
}
if (uuid == kHeartGoldUsUuid || uuid == kSoulSilverUsUuid) {
    return &kHgssPack;
}
if (uuid == kBlackUsUuid || uuid == kWhiteUsUuid) {
    return &kBwPack;
}
if (uuid == kBlack2UsUuid || uuid == kWhite2UsUuid) {
    return &kB2w2Pack;
}
if (uuid == kSacredGoldUuid) {
    return &kSgPack;
}
if (uuid == kRenegadePlatinumUuid) {
    return &kRenplatPack;
}
if (uuid == kPlatinumKaizoUuid) {
    return &kPtkaizoPack;
}
if (uuid == kBlazeBlackUuid) {
    return &kBlazePack;
}
if (uuid == kVoltWhiteUuid) {
    return &kVoltPack;
}
if (uuid == kVoltWhite2ReduxUuid) {
    return &kVw2Pack;
}
if (uuid == kEmeraldKaizoUuid) {
    return &kEmkaizoPack;
}
if (uuid == kFireRedOmegaUuid) {
    return &kFroPack;
}
if (uuid == kRadicalRedUuid) {
    return &kRrPack;
}
if (uuid == kUnboundUuid) {
    return &kUnboundPack;
}
